import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import { LayoutProps } from "@/types/Layout";

import "./globals.css";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {/* <Toaster richColors position="top-center" /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
